# Generated by Django 5.0.6 on 2024-09-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='car',
            new_name='book',
        ),
    ]
